### ISSUE TITLE
Refactor state to be passed explicitly to test_* functions

### ISSUE THREAD

**Issue by machow** [datacamp/pythonwhat#101]
This is almost complete..

## Todo/test

- [x] Importing w/in sub tests, when run in new process (not an issue, due to initial evaluation)
- [x] test_try_except dictionary of sub tests
- [x] look back through test_test_intermediate to add more tests
- [ ] clean up test_exercise and probe.py
- [ ] remove redundant handling of lists of sub tests, leave only in sub_test
- [ ] pass state as argument to getRepresentation (in tasks.py)
- [ ] rename tree to _TREE in sct_cntxt
- [x] NodeList and NodeDict
- [x] all tests passing

### Simplify complex lambda behavior

Original

```
# run test_if_else in loop
msg = "In the condition of your `if` part, make sure you use `dice <= 2`."
for i in range(1,7):
    test_if_else(1, test = lambda msg=msg, i=i: test_expression_result({"dice": i}, incorrect_msg = msg), 
    expand_message = False)
```

New

```
# use list comprehension of sub tests
msg = "In the condition of your `if` part, make sure you use `dice <= 2`."
test_if_else(1, 
             test = [test_expression_result({"dice": i}, incorrect_msg = msg) for i in range(1,7)], 
             expand_message = False)
```

**Comment by machow** [comment]
@hugobowne @filipsch can you point me to an example of needing imports in a sub test? It sounded like...

```
def inner_test():
    import pandas as pd
    # more here...
    test_of_some_kind(dataframe_var)
```

**Comment by filipsch** [comment]
@machow it's discussed in [this issue](https://github.com/datacamp/pythonwhat/issues/83)

**Comment by machow** [comment]
@filipsch I tried to create a minimal test case where imports in a sub test are necessary but it didn't seem to need it...
```python

import helper

data = dict(
    DC_PEC =      """import pandas as pd; import numpy as np """,
    DC_CODE =     """def f(df): df += 1""",
    DC_SOLUTION = """def f(df): df += 1""",
    DC_SCT =      """
import pandas as pd
def inner_test():
    test_df = pd.DataFrame({'a': [0]})
    test_object_after_expression("df", context_vals = [test_df]) 

test_function_definition("f", body = inner_test)

success_msg("Great work!")
    """
)

payload = helper.run(data)
print("SCT Passed:" , payload['correct'])

```

Any idea what I might have missed?

**Comment by filipsch** [comment]
@machow Hm, strange stuff. Maybe your refactor up to now magically solved it?
