### ISSUE TITLE
Example SCTs in documention

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#103]
In #102, I asked a bunch of questions about writing  SCTs for list comprehensions. E.g. how do I write SCTs for:

`L2 = [i**2 for i in range(0,10) if i>2]`.

It would be great to include in the wiki a narrative of how to write SCTs for these types of cases.

We could start with  `L1 = [i**2 for i in range(0,10)]` then `L2 = [i**2 for i in range(0,10) if i>2]`, then `L3 = [i**2 if i>5 else 0 for i in range(0,10) if i>2]` and so on.

It would be good to have such examples for all functions and I am in the perfect position to help with development of this. I think the timing is perfect as @machow is currently learning a great deal about this and we could write the documentation together. 

Pythonwhat has come an incredible distance (many thanks to @vincentvankrunkelsven & @filipsch) in the past 6months and, as a user, the rate-limiting step is currently the documentation.

I suggest a process whereby we use all my questions on this issue tracker and their solutions to build out the wiki. We could also build a DataCamp course on using pythonwhat in the future!

**Comment by filipsch** [comment]
@hugobowne there is already a datacamp course on using pythonwhat, see the link at the bottom of the getting started article of the wiki.

But you're right, documentation is important! Addig basic examples is going to be the quickest and most effective win I think.

**Comment by machow** [comment]
using this to track wiki progress.



- [ ] [page on parts](https://github.com/datacamp/pythonwhat/wiki/SCT-Tutorial), using list comprehensions (see #102)
- [ ] splat operator (see #104)
- [ ] testing a list passed as argument (e.g. SQLAlchemy, see #99)

**Comment by machow** [comment]
see edit above for links to docs.
